version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: learn_rails
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: 
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/opt/app  

volumes:
  postgres_data: